name: Deploy Production Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Production Theme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Upload theme
        env:
          SHOPIFY_PRODUCTION_THEME_ID: ${{ vars.SHOPIFY_PRODUCTION_THEME_ID }}
          SHOPIFY_STORE_URL: ${{ vars.SHOPIFY_STORE_URL }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
        run: |
          shopify theme push \
            --json \
            --theme $SHOPIFY_PRODUCTION_THEME_ID \
            --store $SHOPIFY_STORE_URL \
            --password $SHOPIFY_PASSWORD \
            --allow-live
