name: Deploy Staging Theme

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy Staging Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v2
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.1.3
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY__PASSWORD }}
          SHOPIFY_STORE_URL: ${{ vars.SHOPIFY__STORE_URL }}
          SHOPIFY_THEME_ID: ${{ vars.SHOPIFY_STAGING_THEME_ID }}
          THEME_PATH: ${{ vars.THEME_PATH }}
        with:
          args: --ignored-file=config/settings_data.json --ignored-file=locales/*